### ISSUE TITLE
wrangler generate template support main branch

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler-legacy#1704]
Instead of default to the master branch we should check for the main branch first or allow the user to provide the branch's name

**Comment by p-j** [comment]
Hi @xtuc 
I've made a pull request for that a couple of month ago, still waiting for it to be acknowledge though.
https://github.com/cloudflare/wrangler/pull/1653
Happy to take feedbacks in and help move this forward, that's actually an issue for a template I've made and use for some of my projects.

**Comment by jldec** [comment]
Hi,
I'm hitting this while following the [docs for durable objects](https://developers.cloudflare.com/workers/learning/using-durable-objects) which is using https://github.com/cloudflare/durable-objects-template

```
$ wrangler generate rate-limit-actions https://github.com/cloudflare/durable-objects-template
🔧   Creating project called `rate-limit-actions`...
Error: ⛔   Git Error: failed to find branch `master`                                                                                                     
Error: tried running command:
/Users/jleschner/Library/Caches/.wrangler/cargo-generate-0.5.0/cargo-generate generate --git https://github.com/cloudflare/durable-objects-template --name rate-limit-actions --force
exited with exit code: 1
```

**Comment by jldec** [comment]
see https://discord.com/channels/595317990191398933/799437470004412476/828395478244524082

**Comment by jyn514** [comment]
Github actually lets you determine the primary branch automatically, there's no need to hard-code `main` or `master`. The latest version of `cargo-generate` does this automatically:
```
$ cargo generate --git https://github.com/cloudflare/websocket-template --name websocket
⚠️   Unable to load config file: /home/jnelson/.local/lib/cargo/cargo-generate.toml
🔧   Generating template ...
[ 1/14]   Done: .github/workflows/deploy.yml
[ 2/14]   Done: .github/workflows
[ 3/14]   Done: .github
[ 4/14]   Done: .gitignore
[ 5/14]   Done: .prettierrc
[ 6/14]   Done: CODE_OF_CONDUCT.md
[ 7/14]   Done: LICENSE_APACHE
[ 8/14]   Done: LICENSE_MIT
[ 9/14]   Done: README.md
[10/14]   Done: index.js
[11/14]   Done: package-lock.json
[12/14]   Done: package.json
[13/14]   Done: template.js
[14/14]   Done: wrangler.toml
🔧   Moving generated files into: `/home/jnelson/src/wrangler/websocket`...
✨   Done! New project created /home/jnelson/src/wrangler/websocket
```
So we just need to update it from 0.5 to 0.11.

**Comment by zashraf1985** [comment]
I am facing the same issue. Can you merge the PR ASAP.

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
