### ISSUE TITLE
`dev` fails with a websocket redirect error

### ISSUE THREAD

**Issue by viraptor** [cloudflare/wrangler-legacy#1711]
#### Environment

* operating system: macos
* output of `rustc -V`: 1.47.0
* output of `node -v`: v14.15.1
* output of `wrangler -V`: 1.12.3 / master
* contents of `wrangler.toml` 

```
name = "service_id"
type = "webpack"
account_id = "..."
workers_dev = true
route = "some_domain.net/*"
zone_id = "..."

kv_namespaces = [
  { binding = "KV", id = "...", preview_id = "..." }
]
```

#### Steps to reproduce

```
wrangler dev
```

#### What did you expect to see?

Service to start up

#### What did you see instead?

```
thread 'tokio-runtime-worker' panicked at 'Failed to connect to devtools instance: Http(302)', src/commands/dev/socket.rs:30:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
👂  Listening on http://127.0.0.1:8787
Error: panic
```
This is triggered in `src/commands/dev/socket.rs:28` / `wrangler::commands::dev::socket::listen::{{closure}}`

Unfortunately due to `tokio-tungstenite` returning only the status, I don't know exactly what the contents are.
It may be related however due to us using access authentication on the domain. If I print out the url wrangler is trying to connect to (`https://some_domain.net/cdn-cgi/workers/preview/inspector?f_workers_preview_token=...`) and try to `curl` it, I can see:

```
< HTTP/2 302
...
< location: https://....cloudflareaccess.com/cdn-cgi/access/login/some_domain.net
```

which I expect is the same redirect wrangler sees.

**Comment by lukevalenta** [comment]
I was able to work around this issue by not simultaneously specifying both `zone_id` and `workers_dev` when running `wrangler dev`.

A configuration like this works:
```
name = "service_id"
type = "webpack"
account_id = "..."
route = "some_domain.net/*"

kv_namespaces = [
  { binding = "KV", id = "...", preview_id = "..." }
]

[env.dev]
workers_dev = true

[env.prod]
zone_id = "..."
```

And then run `wrangler dev --env dev`

**Comment by viraptor** [comment]
Stay away, bot!

**Comment by jgentes** [comment]
We made some updates to websockets support.. is this still an issue?

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
