### ISSUE TITLE
get kv metadata

### ISSUE THREAD

**Issue by ags799** [cloudflare/wrangler-legacy#1751]
### 💡 Feature request
We can put KV metadata with
```
wrangler kv:key put --namespace-id $id some-key some-value -m '"metadata"'
```
It makes sense to add functionality to get metadata, too. I'm thinking
```
wrangler kv:key get --metadata --namespace-id $id some-key
```
which would print metadata to STDOUT, instead of the value.

**Comment by koeninger** [comment]
what about list with metadata?

**Comment by ags799** [comment]
@koeninger separate issue?

**Comment by xortive** [comment]
would it be nice to get both the key and the metadata at the same time? could we output a JSON object with both?

**Comment by ags799** [comment]
@xortive value isn't necessarily valid JSON, it would need to be base-64'd.

**Comment by greg-mckeon** [comment]
The API in a Worker forces you to get both the value and the metadata at the same time, right?  I think I'd prefer keeping the API as similar as possible, which would mean adding metadata list and getWithMetadata, but not a get for metadata alone.

In a Worker today, does getWithMetadata do base 64 encoding?

**Comment by koeninger** [comment]
getWithMetadata in a worker has the same available return types for the
value as get does, ie text. arraybuffer, etc.

It's a little different when we're dealing with standard out on a command
line api.

**Comment by ags799** [comment]
We'll go with
```
wrangler kv:key get-metadata --namespace-id $id some-key
```
And in another issue, list should include metadata.

**Comment by StarpTech** [comment]
Hi, what's the status?

**Comment by samuelcolvin** [comment]
did this ever get fixed?

**Comment by koeninger** [comment]
probably better to re-open on https://github.com/cloudflare/wrangler2

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
