### ISSUE TITLE
[custom-builds-rc] handling of configuration options that don't work in modules mode

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler-legacy#1842]
- `text_blobs`
- `wasm_modules` added by https://github.com/cloudflare/wrangler/pull/1803

These options do not have meaning in `modules` mode. It is unclear what module path we should use for them, as they may not be inside `upload_dir`. We should warn if they are present when in modules mode.

**Comment by ItsiAdam2** [comment]
> These options do not have meaning in `modules` mode.

Do they not work at all then? Is there any reason that they shouldn't?
The path should just be relative, like any other binding...

**Comment by ItsiAdam2** [comment]
This should definitely error and explain that imports should be used instead. I would also suggest that documentation is created to explain how to properly use WASM in modules.

**Comment by admah** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
