### ISSUE TITLE
Contributing guidelines outdated

### ISSUE THREAD

**Issue by arunesh90** [cloudflare/wrangler-legacy#1901]
Hello 🙂

While making my first PR for this repo, I noticed while reading the [contributing guidelines](https://github.com/cloudflare/wrangler/blob/master/CONTRIBUTING.md) that both core contributors it mentions are no longer employees at Cloudflare and do not seem to maintain/contribute to this repo anymore.

> # People
> .... **The core maintainers are @.EverlastingBugstopper and @.ashleymichal** ...

(Added a dot between the mentions to not accidentally bother them with a notification)

**Comment by Electroid** [comment]
Hello, thanks for reporting this. We indeed have new maintainership, we'll get this updated.

**Comment by arunesh90** [comment]
Bumping this as the documentation is still stale 🙂

**Comment by admah** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
