### ISSUE TITLE
Bulk Read / Export

### ISSUE THREAD

**Issue by turbo** [cloudflare/wrangler-legacy#1957]
#### Describe the feature

Building a production app on Workers requires a strategy for exporting data from KV. Currently, I have 300k+ keys in a project and I see no way to get this data out of Workers again. Wrangler has a bulk set, but not a bulk read. This is an issue for several reasons:

- Data portability: no reasonable way to export data at all (short of using several runs of expensive/high-memory Unbound workers)
- Redundancy: No way to back up data for later disaster recovery - one wrong click in e.g. the namespace UI and your entire dataset is gone

FWIW, even just using wrangler to list keys takes several minutes on this namespace. Lastly, I don't think this use case is unreasonable, as CF points out that the keyspace for namespaces is "unlimited" in several places.

For the export format, I suggest supporting JSONL and/or CSV.

#### Describe the alternatives

See above for hacks, otherwise, there are no viable alternatives.

**Comment by koeninger** [comment]
I think this is a reasonable feature request, but regarding "one wrong click in e.g. the namespace UI," deletion of namespaces in the UI requires typing in the name of the namespace to be deleted, it's not one click.

In the meantime, you could modify https://github.com/cloudflare/kv-worker-migrate to write the data wherever you need it.

**Comment by syffs** [comment]
@koeninger I feel like there's no good reason for a storage solution offered by a company like Cloudflare, not to provide any straightforward way to export/backup data.

There are [threads](https://community.cloudflare.com/t/kv-external-backups/114361) on the community forum that have been pending for months / years.

Any ETA on such a basic feature ?

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
