### ISSUE TITLE
Consider using cargo-generate v0.6.0+

### ISSUE THREAD

**Issue by jashandeep-sohi** [cloudflare/wrangler-legacy#2003]
#### Describe the feature

Currently `wrangler generate ...` calls out to `cargo-generate` v0.5.0 to template out any files.
From v0.6.0+ `cargo-generate` supports template defined [placeholders](https://github.com/cargo-generate/cargo-generate#template-defined-placeholders) (aka custom variables) that allows template authors to better customize templates based on user prompts.

Would it be possible to bump the dependency on `cargo-generate` to at least v0.6.0 (but preferably to the latest release)?

#### Describe the alternatives

My hack was to copy over a build of `cargo-generate` (v0.7.0) to `$HOME/.cache/.wrangler/cargo-generate-0.5.0/cargo-generate`. Not really a solution, but a good way to test out things without making any code changes.

**Comment by nilslice** [comment]
@jashandeep-sohi - thanks for the suggestion! I'll try it out and see if there is any objection to doing this.

**Comment by Electroid** [comment]
I think our blocker right now is that cargo-generate does not distribute already-built binaries through GitHub releases (like it use to)

**Comment by jashandeep-sohi** [comment]
> I think our blocker right now is that cargo-generate does not distribute already-built binaries through GitHub releases (like it use to)

Hopefully since v0.7.2 it should :wink: https://github.com/cargo-generate/cargo-generate/releases/tag/v0.7.2

**Comment by nilslice** [comment]
Thanks for adding that back @jashandeep-sohi! I'll update our tracking ticket to get this tested. Will update here with progress asap.

**Comment by admah** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
