### ISSUE TITLE
Durable objects paid errors

### ISSUE THREAD

**Issue by janat08** [cloudflare/wrangler-legacy#2074]
#### Describe the feature
Warn that exporting durable object classes is pointless on free plan. I simple get undefined when trying to use itty durable assuming I did something wrong. 

#### Describe the alternatives
Warn once the package is installed on free plan. Allow using it in development.

**Comment by ptim** [comment]
`wrangler` has progressed since this was filed, but the experience (understandably) still has some sharp edges - I got:

> `wrangler dev`
> ...
> Error: Something went wrong with the request to Cloudflare...
> cannot bind Durable Object by class name in preview upload of script that does not already exist [API code: 10074]

resolved that with:

> `wrangler publish`
> ...
> Your account does not have permission to do this! While Durable Objects are in Beta, the modules format is limited to accounts which have opted-in to the Beta. You may do so by following the instructions here: https://developers.cloudflare.com/workers/learning/using-durable-objectsworkers.api.error.not_entitled [API code: 10015]

I do have a paid account, and just needed to opt in to Durable Objects (at the Org level, IIRC). Note that the URL in the error is broken :)

**Comment by JacobMGEvans** [comment]
Thanks for creating this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this PR.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it or create a new PR in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

If you want to use Durable Objects in development on a free plan, use `npx wrangler dev --local`.
