### ISSUE TITLE
Cloudflare 304 response conflicts with HTMLRewrite

### ISSUE THREAD

**Issue by FernetB** [cloudflare/wrangler-legacy#2083]
#### Describe the bug

I'm not enterely sure that is a bug, but I can't find the answer for that.

I'm using the HTMLRewirte to insert the locale into a data-country on the html
that works fine but the problem is that the enterely html is cached because cloudflare returns a 304 revalidated and therefore if the user changes the ip will not see any change in the locale.

#### Reproduce the bug
This is the last function used to serve the page
```js
class ElementHandler {
  constructor(request) {
    this.request = request;
  }
  element(element) {
    const countryCode = getCountrySufix(this.request);
    if (countryCode) element.setAttribute("data-country", countryCode);
    else element.setAttribute("data-country", "ar");
  }
}

export const servePage = async (event) => {
  try {
    const response = await getAssetFromKV(event, {
      mapRequestToAsset: serveSinglePageApp,
    });
    return new HTMLRewriter()
      .on("div#root", new ElementHandler(event.request))
      .transform(response);
  } catch (e) {
    const pathname = new URL(event.request.url).pathname;
    return new Response(`"${pathname}" not found`, {
      status: 404,
      statusText: "not found",
    });
  }
};
```

#### Expected behavior

I don't know exactly where cloudflare check if the hash build is the same as the hash provided by the request header
```json
if-none-match: W/"index.2c0a40d7fd.html"
```
but why this does not change if the HTMLRewrite returns something different because it sets a different attribute

Environment and versions
Fill out the following information about your environment.

operating system: Ubuntu 20.04
output of node -v: v14.17.6

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
