### ISSUE TITLE
wrangler installs and uses older version of wasm-pack

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [cloudflare/wrangler-legacy#2098]
### 🐛 Bug report

```
❯ wrangler --version
👷 ✨  wrangler 1.13.0
```

#### Describe the bug
wrangler installs and then uses an older version of wasm-pack that the version I already have installed via cargo/shell and then prints a warning to the user....

```
wrangler dev                                                                           
⬇️   Installing wasm-pack v0.9.1...
🌀  Compiling your project to WebAssembly...
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling rustwasm-markdown-parser v0.1.0 (/Users/andrew/workspace/napa/rustwasm-markdown-parser)
    Finished release [optimized] target(s) in 0.90s
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional field missing from Cargo.toml: 'repository'. This is not necessary, but recommended
[INFO]: ✨   Done in 2.24s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/andrew/workspace/napa/rustwasm-markdown-parser/pkg.
⚠️   [WARN]: There's a newer version of wasm-pack available, the new version is: 0.10.1, you are using: 0.9.1. To update, navigate to: https://rustwasm.github.io/wasm-pack/installer/
```

#### Reproduce the bug

1. Install latest wasm-pack `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`
2. Force install the latest version of wrangler `cargo install --force wrangler`
3. Run `wrangler dev` on a project 

#### Expected behavior

Uses the version of wasm-pack in my $PATH (if using an executable) or the latest crate (if using as a lib)

#### Environment and versions
Mac OS 11.14     
cargo 1.55.0 (32da73ab1 2021-08-23)

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
