### ISSUE TITLE
thread '<unnamed>' panicked at '--watch change message failed to send: "SendError(..)"'

### ISSUE THREAD

**Issue by lovasoa** [cloudflare/wrangler-legacy#2111]
Sometimes, wrangler crashes with `thread '<unnamed>' panicked at '--watch change message failed to send: "SendError(..)"', src/wranglerjs/mod.rs:111:41`

**Comment by caass** [comment]
Hey! Wanted to let you know we're looking into this after we're able to resolve our issues with the RUSTSEC. You're not screaming into the void!

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
