### ISSUE TITLE
Wranger generate errors with segmentation fault when installing cargo-generate

### ISSUE THREAD

**Issue by spacecowboy** [cloudflare/wrangler-legacy#2147]
#### Describe the bug

When running `wrangler generate my-app https://github.com/cloudflare/worker-typescript-template` I encounter a segmentation fault:

```
$ wrangler generate my-app https://github.com/cloudflare/worker-typescript-template
⬇️   Installing cargo-generate v0.5.0...
Segmentation fault (core dumped)
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create a new empty folder
2. Inside folder run VS Code: `code .`
3. In VS Code, configure a new DevContainer. Select a `Node-16` container, with `Rust` selected as an extra feature.
4. Once project is reopened in the container, open a new terminal and install wrangler: `cargo install wrangler`
5. Attempt to generate a typescript project: `wrangler generate my-app https://github.com/cloudflare/worker-typescript-template`

#### Expected behavior

Project template is generated, no segmentation faults

#### Environment and versions

Fill out the following information about your environment.

* operating system: Debian Buster, running a Docker container with Debian Bullseye
* output of `wrangler -V`: `wrangler 1.19.5`
* output of `node -v`: `v16.13.1`
* content of `wrangler.toml`: No such file exists - I am trying to generate it

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
