### ISSUE TITLE
Webpack 5 / Future plans regarding webpack

### ISSUE THREAD

**Issue by brillout** [cloudflare/wrangler-legacy#2158]
I know the current recommendation is to either use wrangler's webpack v4 based bundler or a custom build/bundler.

Do you plan to make wrangler's bundler use webpack 5 instead of webpack 4?

My users (I'm the author of [`vite-plugin-ssr`](https://vite-plugin-ssr.com/)) are confused about what you officially recommend to do. Do you plan to deprecated webpack? Or will wrangler migrate to webpack 5?

I know the official docs say that you will continue support the "webpack" build. But webpack v4 is already starting to become "deprecated software" (e.g. it doesn't seem to support `package.json#exports`). So wrangler will, sooner rather than later, have to decide to either deprecate webpack altogether or migrate to webpack 5.

Some clarification would be nice so we can properly invest in the right tools.

**Comment by threepointone** [comment]
I can provide some clarity here. 

wrangler will not be updating the webpack dependency to webpack 5. Further, we'll be phasing out support for the `type` field in `wrangler.toml`. (the type `rust` already is the same code path as the `javascript` code path, in that you need to define a build command anyway)

wrangler 2 (in active development at https://github.com/cloudflare/wrangler2) comes with esbuild internally, so a number of common usecases for a bundler (modules, npm dependencies, jsx, stripping types etc) work out of the box for entry points. You can still use your own build systems, and point wrangler at the output of that, of course. 

We will provide an automated `eject` script for existing projects that use `type = "webpack"` so as to not break existing projects; thus also giving consumers a way to upgrade their webpack dependency themselves if they so prefer.

Once we start rolling out wrangler 2 (in early 2022), we will also amend the documentation and starter kits to reflect this guidance. 

I'll also comment on the linked issue (https://github.com/brillout/vite-plugin-ssr/issues/217) re: guidance around streaming in a bit, but I hope the above is clear. 

I'll assign this issue to myself leave this issue open until we have documentation regarding the deprecation and the automatic ejection/transition. Happy to answer any more questions.

**Comment by brillout** [comment]
That's super helpful, thanks for the thorough insights.

**Comment by penalosa** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
