### ISSUE TITLE
cargo install wrangler fails on Fedora 35

### ISSUE THREAD

**Issue by darragh-downey** [cloudflare/wrangler-legacy#2186]
#### Describe the bug

`error:` failed to run custom build command for `openssl-sys v0.9.72

Caused by:
  process didn't exit successfully: `/tmp/cargo-installfrgjug/release/build/openssl-sys-b87e00376dda7a4b/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/tmp/cargo-installfrgjug/release/build/openssl-sys-20a60254477a46dd/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"

  --- stderr
  Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /usr/local/lib64/perl5/5.34 /usr/local/share/perl5/5.34 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./Configure line 15.
  BEGIN failed--compilation aborted at ./Configure line 15.
  thread 'main' panicked at '

  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=/tmp/cargo-installfrgjug/release/build/openssl-sys-20a60254477a46dd/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
      Exit status: exit status: 2

      ', /home/ddowney/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.17.0+1.1.1m/src/lib.rs:479:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wrangler v1.19.7`, intermediate artifacts can be found at `/tmp/cargo-installfrgjug`

Caused by:
  build failed`

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Execute `cargo install wrangler`

#### Expected behavior

Install Wrangler

#### Environment and versions

Fill out the following information about your environment.

* operating system: Fedora 35
* cargo version: cargo 1.58.0 (7f08ace4f 2021-11-24)
* rust version: rustc 1.58.0 (02072b482 2022-01-11)
* output of `perl --version`:  This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-thread-multi

#### Resolved

The `FindBin` module comes packaged as part of `perl-core`. Unfortunately it does not appear as though `perl-core`  was installed by default, although the `perl` interpreter was.

Resolved by installing `perl-core`:
`sudo dnf install perl-core`

Which allowed `wrangler` to be installed using `cargo`:
`cargo install wrangler`

#### Suggestion

Update documentation to prompt user to ensure `perl-core` is installed prior to running `cargo install wrangler` on Linux.

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
