### ISSUE TITLE
wrangler dev throws permission denied, wsl2

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [cloudflare/wrangler-legacy#2206]
#### Describe the bug

when generating a fresh project with `wrangler generate --type="rust"`  and trying to use `wrangler dev` I get the following output

``` #/bin/sh
🌀  Running cargo install -q worker-build && worker-build --release
Error: Permission denied (os error 13)
Error: Build failed! Status Code: 1
```

#### Reproduce the bug

1. `wrangler generate`
2. `cd into-project && wrangler dev`

#### Expected behavior

This should start the dev server 

#### Environment and versions

Fill out the following information about your environment.

* operating system: windows WSL2
* output of `wrangler -V`:  wrangler 1.19.8
* output of `node -v`: **v17.6.0**
* content of `wrangler.toml`: 

```
name = "test"
type = "javascript"
workers_dev = true
compatibility_date = "2022-02-27"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
```

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
