### ISSUE TITLE
Wrangler should support publishing without building first

### ISSUE THREAD

**Issue by ksnll** [cloudflare/wrangler-legacy#2219]
#### Describe the feature

`wrangler publish` should support publishing without building the worker first.

Currently, running `wrangler publish`, will always run the build script before publishing the worker.

This works fine locally, but in a CI environment, it prevents easily publishing a previously compiled version of the worker. 
The reasoning for doing that is that when rolling back production versions, it feels much safer to redeploy something that was already compiled/bundled and tested, rather than recompiling again from scratch. It's also faster and it will skip any possible issues with the build pipeline itself.

So a possible workflow on CI could be
- Build the worker 
- Save the built version of the worker as an artifact
- Deploy the artifact

Rolling back would mean only:
- Choose the version of the artifact you want to roll back
- Deploy the artifact

#### Describe the alternatives

The only reasonable alternative I see is to build every time before publishing or use the workers api instead of wrangler to upload the script

**Comment by Hebilicious** [comment]
100% agree that no build flag would be ideal in the situations where you want to build the worker, run integrations tests against it, then deploy it. 
Altough with esbuild we're only talking about 1s build time, may I suggest a `--no-build` or `--build=false` flag ?

**Comment by threepointone** [comment]
I think a better answer here is for the Workers platform to support versioned deploys, so you can revert publishes and so on. It's something we're actively exploring at the moment.

**Comment by leviwolfe** [comment]
Another important use case for a true `--no-build` flag is re-using immutable artifacts. When my code changes, I want my CI to build a single artifact one time. I deploy that artifact to dev, test it, and want to deploy *the exact same artifact* to staging, test again, and deploy *the exact same artifact* to production. If every `wrangler publish` also rebuilds, then I reduce confidence that what I deploy is the same as what I just tested.

My current workaround has been to set the following in wrangler.toml:
```
[build]
command = ""
```
And something like this in package.json for local development:
```
"start": "miniflare --build-command \"pnpm install && pnpm run build\""
```

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

In Wrangler v2+, the [`--no-bundle`](https://github.com/cloudflare/workers-sdk/pull/1300) flag should cover your needs
