### ISSUE TITLE
wrangler site include dir not work for '/dir'

### ISSUE THREAD

**Issue by YaaMe** [cloudflare/wrangler-legacy#2220]
#### Describe the bug

for file `./build/dir/index.html`
```
[site]
bucket = "./build"
entry-point = "workers-site"
include = ["/dir"] # <= it not work
# include = ["dir"] # <= also not work
# include = ["dir/*"] # <= it work
```

as [docs](https://developers.cloudflare.com/workers/platform/sites/configuration/#ignoring-subsets-of-static-assets) said, gitignore style for a folder
```
[package]
# ...
include = ["/src", "COPYRIGHT", "/examples", "!/examples/big_example"]
```
It seems like a bug.

#### Environment and versions
$ wrangler --version
wrangler 1.19.8

$ node -v
v15.14.0

**Comment by jspspike** [comment]
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
