### ISSUE TITLE
Error: Your JavaScript project is missing a `package.json` file

### ISSUE THREAD

**Issue by billymaulana** [cloudflare/wrangler-legacy#2236]
#### Describe the bug
when im build `wrangler publish` i get this error:
`Error: Your JavaScript project is missing a `package.json` file; is `/Users/projet/.output/server/index.mjs` the wrong directory?`
#### Reproduce the bug
my package.json:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/13347455/163225802-14bceb6e-3fe8-494c-8ad1-2546272d8064.png">

workers dir:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/13347455/163225875-23b33397-60d4-4741-bdc1-cda4fcc57ed2.png">

#### Environment and versions
* output of `wrangler -V`:1.19.11
* output of `node -v`:v16.14.2
* content of `wrangler.toml`:

my wrangler.toml
<img width="395" alt="image" src="https://user-images.githubusercontent.com/13347455/163225224-871e1618-67ee-4f45-8e45-9941f802ec35.png">

**Comment by pipeu** [comment]
Thanks!
