### ISSUE TITLE
Indicate where "Buffer" is undefined inside of node_modules

### ISSUE THREAD

**Issue by vedantroy** [cloudflare/wrangler-legacy#2247]
#### Describe the feature

A clear and concise description of the feature. What problem does it solve for you?

Cloudflare workers will throw errors about buffer being undefined. That makes sense since the workers env doesn't support buffer, but I'd like to know in which node_module my app is requiring buffer is being used. This would make it significantly easier to debug.

#### Describe the alternatives

Are there any alternatives to solving this problem? If so, what was your experience with them?

Manually searching through node_modules. Takes forever.

Also throw error if config file is missing.

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

Nodejs compat is improving, and we'll soon have an implementation of `Buffer` you can use from within workers!
