### ISSUE TITLE
Generate shell completions

### ISSUE THREAD

**Issue by pkoch** [cloudflare/wrangler-legacy#2265]
### 💡 Feature request

Generate shell completions for bash/zsh/fish/etc, whatever [clap_complete](https://docs.rs/clap_complete/latest/clap_complete/) supports.

#### Describe the feature

In order to make the CLI easier to use and feel modern, I want to be able to use tab-complete on wrangler in my shell.

#### Describe the alternatives

Keep checking the docs, be slowed down.

**Comment by pkoch** [comment]
It feels very suspicious this is not already implemented. Is there any known blocker? Would the maintainers be open to a PR that adds something like `wrangle complete $SHELL`?

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

The relevant issue for Wrangler v2+ is https://github.com/cloudflare/workers-sdk/issues/53
