### ISSUE TITLE
Tracking issue for `rust-toolchain` version

### ISSUE THREAD

**Issue by caass** [cloudflare/wrangler-legacy#2308]
Updating the `rust-toolchain` version also means updating dependencies to avoid [breakage](https://github.com/rust-lang/rust/pull/78802). We should avoid bumping the `rust-toolchain` version until dependencies are up to date.

**Comment by JacobMGEvans** [comment]
Thanks for creating this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this PR.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it or create a new PR in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).
