### ISSUE TITLE
Allow routes to be excluded 

### ISSUE THREAD

**Issue by alexandrukis** [cloudflare/wrangler-legacy#2323]
### 💡 Feature request
Sorry if I am spamming, since this is a 1-to-1 copy of this issue: https://github.com/cloudflare/wrangler/issues/1817 (I couldn't find any way of simply re-opening this one).

Basically, I am looking for a way of excluding some routes from the workers (like images, static assets, etc.) using a `wrangler.toml` file.

Taking this URL structure as an example:

```
host.com/images/              - no worker
host.com/some-static-assets/  - no worker

host.com/api/                 - worker
host.com/location-1/          - worker
...
host.com/location-N/          - worker
```

it is very hard to enumerate all possible URLs, just so `/images/` and `/some-static-assets/` are ignored.

Is there any way of achieving this?

Thank you!

**Comment by ivstiv** [comment]
We also need this, shame that nobody has replied.. Are there any escape hatches to get this behaviour?

**Comment by penalosa** [comment]
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

It looks like https://github.com/cloudflare/workers-sdk/issues/1319 might cover your suggestion for v2+?
