### ISSUE TITLE
Cloning existing project using wrangler CLI.

### ISSUE THREAD

**Issue by fira-pro** [cloudflare/wrangler-legacy#2346]
I created worker and I added my code through quick edit from cloudflare dashboard. 

I want to clone this existing project to local machine and after some development I want to deploy it back using wrangler CLI. But I couldn't find this cloning feature in wrangler CLI. Any idea what should I do?

**Comment by rozenmd** [comment]
Hey @fira-pro, this is a feature of wrangler 2 - you can check it out here: https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler

`wrangler init --from-dash <name-of-worker>` should do the trick

Note that wrangler 1 (this repo) is called `@cloudflare/wrangler` in npm, while wrangler 2 (and all future versions) are just `wrangler`
